# Generated by Django 3.0.3 on 2020-04-03 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='/static/dogImg', upload_to='dogImages')),
                ('size', models.CharField(choices=[('ANY', 'Any'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='ANY', max_length=10)),
                ('breed', models.CharField(max_length=20)),
                ('age', models.CharField(choices=[('PUP', 'Puppy'), (2, '1-2'), (3, '2-5'), (4, '5+')], max_length=10)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('houseTrained', models.NullBooleanField()),
                ('energyLevel', models.CharField(choices=[('H', 'Live Wire'), ('M', 'Average'), ('L', 'Couch Potato')], max_length=20)),
                ('isAvailable', models.BooleanField(default=True)),
                ('isReserved', models.BooleanField(default=False)),
                ('favourites', models.ManyToManyField(related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/static/profileImg', upload_to='profileImages')),
                ('postcode', models.CharField(max_length=10)),
                ('building', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('address', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, choices=[('ANY', 'Any'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='ANY', max_length=10, null=True)),
                ('age', models.CharField(blank=True, choices=[('PUP', 'Puppy'), (2, '1-2'), (3, '2-5'), (4, '5+')], max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('houseTrained', models.NullBooleanField()),
                ('energyLevel', models.CharField(blank=True, choices=[('H', 'Live Wire'), ('M', 'Average'), ('L', 'Couch Potato')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle', models.CharField(choices=[('H', 'Active'), ('M', 'Average'), ('L', 'Sedentary')], max_length=10)),
                ('timeAway', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('house', models.CharField(choices=[('APT', 'Apartment'), ('HO', 'House')], max_length=10)),
                ('garden', models.BooleanField()),
                ('hasCat', models.BooleanField()),
                ('hasDog', models.BooleanField()),
                ('cohab', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('hasChildren', models.BooleanField()),
                ('trainer', models.BooleanField()),
                ('dogOwner', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='life', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAD2app.Dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasScores', to='WAD2app.UserPref')),
            ],
            options={
                'unique_together': {('user', 'dog')},
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAD2app.Application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIRST', 'First Visit'), ('COURSE', 'Course'), ('GEN', 'General Visit'), ('ADOPT', 'Pickup Pet')], max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAD2app.Application')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='scoresField',
            field=models.ManyToManyField(through='WAD2app.Scores', to='WAD2app.UserPref'),
        ),
        migrations.AddField(
            model_name='application',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WAD2app.Dog'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
