# Generated by Django 3.0.3 on 2020-04-03 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WAD2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='houseTrained',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
