# Generated by Django 3.0.3 on 2020-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAD2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='scoresField',
            field=models.ManyToManyField(through='WAD2app.Scores', to='WAD2app.UserPref'),
        ),
    ]
