# Generated by Django 3.0.3 on 2020-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAD2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.CharField(choices=[('PUP', 'Puppy'), ('1-2', '1-2'), ('2-5', '2-5'), ('5+', '5+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(blank=True, choices=[('PUP', 'Puppy'), ('1-2', '1-2'), ('2-5', '2-5'), ('5+', '5+')], max_length=10, null=True),
        ),
    ]
