# Generated by Django 3.0.3 on 2020-04-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WAD2app', '0003_auto_20200404_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
